[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
# sqlalchemy.url 은 alembic/env.py 에서 get_rds_url_sync() 로 덮어씀
sqlalchemy.url = postgresql+psycopg2://user:pass@localhost/codewhy

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
